version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx2.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
